# Generated by Django 5.0.1 on 2024-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="fees",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
