# Generated by Django 5.0.1 on 2024-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_student_firstname_student_lastname_teacher_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="picture",
            field=models.ImageField(default="", upload_to="S_picture"),
        ),
    ]
