# Generated by Django 5.0.1 on 2024-05-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_rename_user_student_userid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="mobile",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="mobile",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
