# Generated by Django 5.0.1 on 2024-05-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_principle_picture_alter_student_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="principle",
            name="picture",
            field=models.ImageField(default="default.jpg", upload_to="media/P_Picture"),
        ),
        migrations.AlterField(
            model_name="student",
            name="picture",
            field=models.ImageField(default="default.jpg", upload_to="media/P_Picture"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="picture",
            field=models.ImageField(default="default.jpg", upload_to="media/P_Picture"),
        ),
    ]
