# Generated by Django 5.0.1 on 2024-05-15 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_principle_picture_alter_student_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="date_of_joining",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="date_of_joining",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
